/// Flutter icons ExtraBrandIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExtraBrandIcons
///      fonts:
///       - asset: fonts/ExtraBrandIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExtraBrandIcons {
  ExtraBrandIcons._();

  static const _kFontFam = 'ExtraBrandIcons';
  static const _kFontPkg = null;

  static const IconData csharp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visualstudio = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobephotoshop = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobepremiere = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
