/// Flutter icons PortfolioIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PortfolioIcons
///      fonts:
///       - asset: fonts/PortfolioIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PortfolioIcons {
  PortfolioIcons._();

  static const _kFontFam = 'PortfolioIcons';
  static const _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visualstudio = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobephotoshop = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobepremiere = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_copy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_in_new = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_right = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_up = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unity = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitbucket_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subdirectory_arrow_left = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visualstudiocode = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rails = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruby = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cplusplus = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_1 = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase = IconData(0xf0f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 = IconData(0xf13b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_alt = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitbucket = IconData(0xf171, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_filled = IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_card = IconData(0xf2bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData window_maximize = IconData(0xf2d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData window_minimize = IconData(0xf2d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_alt = IconData(0xf305, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store_ios = IconData(0xf370, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData css3_alt = IconData(0xf38b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play = IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData js_square = IconData(0xf3b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData python = IconData(0xf3e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java = IconData(0xf4e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xf549, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xf559, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_reader = IconData(0xf5da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hackerrank = IconData(0xf5f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf7d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
