//TODO: show a png with a black tint at first... 
//TODO: that black tint goes away on hover... 
//TODO: it also and it displays title of what is being hovered over
//TODO: and it links to that tech stacks page with a link tag